#!/usr/bin/env node
// Regenerate src/game/Words.ts from the OpenSubtitles 2018 Finnish frequency
// list intersected with the Kotus nykysuomen sanalista (lemma base forms).
// The intersection keeps only real dictionary lemmas, dropping inflections,
// proper nouns, and foreign tokens while preserving frequency ordering.
//
// Run: yarn build:words [-- --count N --min L --max L]

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const FREQ_URL =
  "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/fi/fi_50k.txt";
const KOTUS_URL =
  "https://raw.githubusercontent.com/hugovk/everyfinnishword/master/kotus-sanalista_v1/kotus-sanalista_v1.xml";

const FINNISH_LETTERS = /^[a-zåäö]+$/;

function parseArgs(argv) {
  const out = { count: 2000, min: 5, max: 14 };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--count") out.count = Number(argv[++i]);
    else if (a === "--min") out.min = Number(argv[++i]);
    else if (a === "--max") out.max = Number(argv[++i]);
    else throw new Error(`Unknown arg: ${a}`);
  }
  return out;
}

async function fetchText(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${url}: ${r.status} ${r.statusText}`);
  return await r.text();
}

function parseKotus(xml) {
  const set = new Set();
  const re = /<s>([^<]+)<\/s>/g;
  let m;
  while ((m = re.exec(xml)) !== null) set.add(m[1].toLowerCase());
  return set;
}

function parseFreq(text) {
  const out = [];
  for (const line of text.split("\n")) {
    const sp = line.indexOf(" ");
    if (sp < 0) continue;
    out.push(line.slice(0, sp));
  }
  return out;
}

async function main() {
  const { count, min, max } = parseArgs(process.argv.slice(2));

  console.log("Fetching sources...");
  const [freqText, kotusXml] = await Promise.all([
    fetchText(FREQ_URL),
    fetchText(KOTUS_URL),
  ]);

  const kotus = parseKotus(kotusXml);
  const freq = parseFreq(freqText);
  console.log(`Kotus lemmas: ${kotus.size}, frequency entries: ${freq.length}`);

  const selected = [];
  for (const word of freq) {
    if (selected.length >= count) break;
    if (word.length < min || word.length > max) continue;
    if (!FINNISH_LETTERS.test(word)) continue;
    if (!kotus.has(word)) continue;
    selected.push(word);
  }
  console.log(`Selected ${selected.length} / target ${count}`);

  const target = resolve(
    dirname(fileURLToPath(import.meta.url)),
    "../src/game/Words.ts",
  );

  const body =
    "// Generated by scripts/build-words.mjs — do not edit by hand.\n" +
    "// Source: OpenSubtitles 2018 frequency list (hermitdave/FrequencyWords)\n" +
    "// intersected with Kotus nykysuomen sanalista (hugovk/everyfinnishword).\n" +
    "// Regenerate: yarn build:words\n" +
    "\n" +
    'import { randomInt } from "../util/numbers";\n' +
    "\n" +
    "const words = [\n" +
    selected.map((w) => `  "${w}",`).join("\n") +
    "\n];\n" +
    "\n" +
    "export function getNewWord(): string {\n" +
    "  const idx = randomInt(0, words.length);\n" +
    "  return words[idx].toLocaleUpperCase();\n" +
    "}\n";

  await writeFile(target, body, "utf8");
  console.log(`Wrote ${target}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
